### ISSUE TITLE
Compute last 6 years means (extract with DDLpy)

### ISSUE THREAD

**Issue by SiggyF** [openearth/sealevel#2]
- [ ]  Test if we can  extract values from DDL (use ddlpy  cli). For the six main tide gauges (Vlissingen, Hoek van Holland, IJmuiden,  Den Helder, Harlingen, Delfzijl)

- [ ]  Check for measurement frequency change
- [ ]  Compute weighted mean
- [ ]  Compare with PSMSL

**Comment by anamabo** [comment]
First task is completed. The data of the water level for the 6 stations listed above is now in the repository. To check the new  features in cli, pleae, go to the ddlpy repository.

**Comment by anamabo** [comment]
No data were retrieved from the following stations: DELFZL; HARLGN; HOEKVHLD; VLISSGN
