### ISSUE TITLE
use relative path

### ISSUE THREAD

**Issue by dlebars** [openearth/sealevel#22]
At the moment there is one absolute path used in *dutch-sea-level-monitor.ipynb*:

`# directory to the sealevel `
`src_dir = pathlib.Path('~/src/sealevel').expanduser()`

Could it be replaced by a relative path so that we don't need to modify it all the time when we synchronise the code?

**Comment by wstolte** [comment]
sounds good to me.

**Comment by wstolte** [comment]
done
