### ISSUE TITLE
Remove SST time series from report

### ISSUE THREAD

**Issue by dlebars** [openearth/sealevel#28]
In section "Oorzaken zeespiegelverandering/Veranderingen in dichtheid" there is a figure showing global and North Sea sea surface temperature (SST).
I think this is confusing because SST is different from ocean density and SST has no direct relation to sea level so it is outside of the scope of this report.
I suggest to either have no figure for this section or replace it with global ocean heat content (OHC) time series. OHC is very much related to density and to sea level rise.
Let me know what you think. I can prepare the new figure.

**Comment by wstolte** [comment]
Hi Dewi. 
Good point. A reason to include it is: SST drives changes (increase) in ocean heat. In the text, it is mentioned that SST itself is not a cause for sea level rise. 
Nevertheless, I think it is a good idea to add (or replace it by) a figure on OHC. Could you do that? or send me a link where I can get the information?

**Comment by wstolte** [comment]
not planned anymore
