### ISSUE TITLE
Remove sea ice discussion from report

### ISSUE THREAD

**Issue by dlebars** [openearth/sealevel#29]
In section "Oorzaken zeespiegelverandering/Massaveranderingen, gletsjers, landijs en zeeijs" there is a long discussion about sea ice and a figure on sea ice area.
There is no direct relation between sea ice and sea level so I think the text and figure can be removed. 
One sentence stating sea ice melt has little direct influence on sea level is enough.
On the other hand, a figure showing Antarctic, Greenland and glaciers mass loss (see Fig. 9.16 a-b and upper left panel of Fig. 9.20 from IPCC AR6 WG1 report) would be very relevant.
I can prepare that figure if necessary.

**Comment by wstolte** [comment]
done
